/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/export_schemas.py from ingest.models
 */

/**
 * Action metric breakdown object in Meta Graph API insights.
 */
export interface MetaAction {
  /** Action type identifier (e.g., 'omni_purchase', 'link_click', 'add_to_cart', 'landing_page_view') */
  action_type: string;
  /** Aggregated count or monetary value of the action */
  value: number;
  /** Conversions attributed within 1-day view window */
  '1d_view'?: number | null;
  /** Conversions attributed within 7-day click window */
  '7d_click'?: number | null;
  /** Conversions attributed within 28-day click window */
  '28d_click'?: number | null;
}

/**
 * Production-exact Meta Graph API /v19.0/{ad_id}/insights record.
 * 
 * Matches attributes returned by the Meta Ads Insights API:
 * spend, impressions, clicks, cpc, cpm, frequency, actions, action_values, date_start, date_stop.
 */
export interface MetaInsightsRecord {
  /** Meta Ad Account ID (act_...) */
  account_id?: string | null;
  /** Meta Campaign ID */
  campaign_id?: string | null;
  /** Meta Campaign Name */
  campaign_name?: string | null;
  /** Meta Ad Set ID */
  adset_id?: string | null;
  /** Meta Ad Set Name */
  adset_name?: string | null;
  /** Meta Ad ID */
  ad_id?: string | null;
  /** Meta Ad Name */
  ad_name?: string | null;
  /** Total ad spend amount in account currency (e.g. USD) */
  spend: number;
  /** The number of times your ads were on screen */
  impressions: number;
  /** The number of clicks on your ads */
  clicks: number;
  /** Average cost per link/all click */
  cpc?: number | null;
  /** Average cost per 1,000 impressions */
  cpm?: number | null;
  /** Average number of times each person saw your ad */
  frequency?: number | null;
  /** Array of action objects (counts for omni_purchase, link_click, etc.) */
  actions?: MetaAction[];
  /** Array of action value objects (monetary value for omni_purchase, etc.) */
  action_values?: MetaAction[];
  /** Start date for the insight metric interval (YYYY-MM-DD) */
  date_start: string;
  /** End date for the insight metric interval (YYYY-MM-DD) */
  date_stop: string;
}

/**
 * Google Ads Campaign resource representation.
 */
export interface GoogleAdsCampaign {
  /** Google Ads Campaign ID (numeric string or int) */
  id: string;
  /** Campaign name */
  name: string;
  /** Channel type: SEARCH, PERFORMANCE_MAX, DISPLAY, SHOPPING, VIDEO */
  advertising_channel_type?: string;
  /** Campaign status: ENABLED, PAUSED, REMOVED */
  status?: string | null;
}

/**
 * Google Ads Segments resource representation.
 */
export interface GoogleAdsSegments {
  /** Date segment formatted as YYYY-MM-DD */
  date: string;
  /** Device segment (DESKTOP, MOBILE, TABLET) */
  device?: string | null;
  /** Day of week segment */
  day_of_week?: string | null;
}

/**
 * Google Ads Metrics resource representation with cost_micros.
 */
export interface GoogleAdsMetrics {
  /** Count of impressions */
  impressions?: number;
  /** Count of clicks */
  clicks?: number;
  /** The sum of your cost-per-click (CPC) and cost-per-thousand impressions (CPM) in millionths of the currency */
  cost_micros?: number;
  /** The number of conversions */
  conversions?: number;
  /** The total value of conversions (monetary sum) */
  conversions_value?: number;
  /** Average cost per click in micro currency or currency units */
  average_cpc?: number | null;
  /** Click-through rate */
  ctr?: number | null;
}

/**
 * Production-exact Google Ads API GoogleAdsRow.
 * 
 * Represents a single row of GoogleAdsService.Search or SearchStream response.
 */
export interface GoogleAdsRow {
  /** Campaign details */
  campaign: GoogleAdsCampaign;
  /** Segments including date */
  segments: GoogleAdsSegments;
  /** Performance metrics */
  metrics: GoogleAdsMetrics;
  /** Google Ads Customer ID (XXX-XXX-XXXX) */
  customer_id?: string | null;
}

/**
 * Production-exact Amazon Advertising API Sponsored Products Report Record.
 */
export interface AmazonSponsoredProductsRecord {
  /** Amazon Campaign ID */
  campaignId: string;
  /** Amazon Campaign Name */
  campaignName: string;
  /** Amazon Ad Group ID */
  adGroupId?: string | null;
  /** Amazon Ad Group Name */
  adGroupName?: string | null;
  /** Amazon Ad ID */
  adId?: string | null;
  /** Amazon Standard Identification Number (e.g., B00...) */
  asin: string;
  /** Merchant Stock Keeping Unit */
  sku: string;
  /** Reporting date (YYYY-MM-DD) */
  date: string;
  /** Total ad impressions */
  impressions?: number;
  /** Total ad clicks */
  clicks?: number;
  /** Ad spend in account currency */
  cost?: number;
  /** Total sales attributed within 14-day window */
  attributedSales14d?: number;
  /** Total units ordered attributed within 14-day window */
  attributedUnitsOrdered14d?: number;
  /** Currency ISO 4217 code */
  currency?: string;
  attributedSales1d?: number | null;
  attributedSales7d?: number | null;
  attributedUnitsOrdered1d?: number | null;
  attributedUnitsOrdered7d?: number | null;
}

/**
 * Line item in a Shopify Order.
 */
export interface ShopifyLineItem {
  /** Shopify Line Item ID */
  id?: string | null;
  /** Shopify Product Variant ID */
  variant_id?: string | null;
  /** Shopify Product ID */
  product_id?: string | null;
  /** Product title */
  title?: string | null;
  /** Product SKU identifier */
  sku: string;
  /** Unit sale price */
  price: number;
  /** Quantity ordered */
  quantity: number;
  /** Total discount applied to this line item */
  total_discount?: number;
}

/**
 * Production-exact Shopify Order payload.
 */
export interface ShopifyOrder {
  /** Shopify Order ID */
  id: string;
  /** Human-readable sequential order number */
  order_number: number;
  /** ISO 8601 UTC creation timestamp */
  created_at: string;
  /** List of purchased line items */
  line_items: ShopifyLineItem[];
  /** Total order amount including taxes and shipping */
  total_price: number;
  /** Subtotal amount before shipping and taxes */
  subtotal_price: number;
  /** Total taxes collected */
  total_tax?: number | null;
  /** Total discounts across the order */
  total_discounts?: number | null;
  /** Currency code (e.g., USD) */
  currency?: string;
  /** Financial status: paid, pending, refunded */
  financial_status?: string | null;
  /** Cancellation timestamp if cancelled */
  cancelled_at?: string | null;
}

/**
 * Shopify Inventory Level and ERP unit COGS model.
 */
export interface ShopifyInventoryLevel {
  /** Shopify Inventory Item ID */
  inventory_item_id: string;
  /** Shopify Location ID */
  location_id: string;
  /** Quantity of inventory items available for purchase */
  available: number;
  /** Associated SKU code */
  sku: string;
  /** Unit Cost of Goods Sold from ERP/Shopify */
  unit_cogs?: number;
  /** ISO 8601 timestamp of inventory update */
  updated_at?: string | null;
}

/**
 * Canonical Unified Commerce Record.
 * 
 * Continuous-time tensor reconciling multi-channel ad spend, conversion attributions,
 * and Shopify storefront transactions/inventory over (timestamp, channel, campaign_id, sku_id).
 */
export interface UnifiedCommerceRecord {
  /** Continuous-time or daily ISO 8601 UTC timestamp */
  timestamp: string;
  /** Ad or commerce channel: 'meta', 'google', 'amazon', 'shopify' */
  channel: string;
  /** Unique campaign identifier */
  campaign_id: string;
  /** Canonical Stock Keeping Unit (SKU) identifier */
  sku_id: string;
  /** Human-readable campaign name */
  campaign_name?: string;
  /** Product / variant title */
  sku_name?: string | null;
  /** Amazon ASIN if mapped */
  asin?: string | null;
  /** Shopify variant ID if mapped */
  variant_id?: string | null;
  /** Currency code (USD) */
  currency?: string;
  /** Total media spend in USD */
  spend?: number;
  /** Ad impressions count */
  impressions?: number;
  /** Ad clicks count */
  clicks?: number;
  /** Cost Per Click */
  cpc?: number;
  /** Cost Per Mille (thousand impressions) */
  cpm?: number;
  /** Click-Through Rate */
  ctr?: number;
  /** Platform-reported attributed conversions */
  ad_conversions?: number;
  /** Platform-reported attributed sales value */
  attributed_revenue?: number;
  /** Platform Return on Ad Spend */
  roas?: number;
  /** Actual physical units sold via Shopify */
  units_sold?: number;
  /** Total gross sales revenue before discounts/tax */
  gross_revenue?: number;
  /** Net revenue collected after discounts */
  net_revenue?: number;
  /** Total promotional discounts applied */
  discounts?: number;
  /** Unit Cost of Goods Sold from ERP */
  unit_cogs?: number;
  /** Total COGS = units_sold * unit_cogs */
  total_cogs?: number;
  /** Gross Margin = net_revenue - total_cogs */
  gross_margin?: number;
  /** Variable payment/fulfillment/shipping fees */
  variable_costs?: number;
  /** Net Contribution Margin (NCM) = net_revenue - total_cogs - spend - variable_costs */
  net_contribution_margin?: number;
  /** Profit on Ad Spend = gross_margin / spend (0 if spend=0) */
  poas?: number;
  /** Marketing Efficiency Ratio = net_revenue / spend (0 if spend=0) */
  mer?: number;
  /** Available stock units at warehouse */
  inventory_on_hand?: number;
  /** Inventory state: 'IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK' */
  inventory_status?: string;
  /** Estimated days of inventory runway remaining based on current velocity */
  days_of_supply?: number | null;
  /** Platform specific raw payload attributes or tracking markers */
  metadata?: Record<string, any>;
}
