#!/usr/bin/env python3
"""Automated JSON Schema & TypeScript interface exporter.

Extracts JSON schemas from Pydantic v2 models and compiles them into
TypeScript interfaces in `web/src/types/` for end-to-end type safety.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Type

# Ensure repository root is on sys.path
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from pydantic import BaseModel

from ingest.models.amazon import AmazonSponsoredProductsRecord
from ingest.models.canonical import UnifiedCommerceRecord
from ingest.models.google import (
    GoogleAdsCampaign,
    GoogleAdsMetrics,
    GoogleAdsRow,
    GoogleAdsSegments,
)
from ingest.models.meta import MetaAction, MetaInsightsRecord
from ingest.models.shopify import ShopifyInventoryLevel, ShopifyLineItem, ShopifyOrder

MODELS: List[Type[BaseModel]] = [
    MetaAction,
    MetaInsightsRecord,
    GoogleAdsCampaign,
    GoogleAdsSegments,
    GoogleAdsMetrics,
    GoogleAdsRow,
    AmazonSponsoredProductsRecord,
    ShopifyLineItem,
    ShopifyOrder,
    ShopifyInventoryLevel,
    UnifiedCommerceRecord,
]


def py_type_to_ts(prop: Dict[str, Any], defs: Dict[str, Any]) -> str:
    """Convert a JSON Schema property definition to a TypeScript type string."""
    # Check for $ref
    if "$ref" in prop:
        ref_name = prop["$ref"].split("/")[-1]
        return ref_name

    # Check for anyOf / oneOf
    if "anyOf" in prop:
        sub_types = [py_type_to_ts(sub, defs) for sub in prop["anyOf"] if sub.get("type") != "null"]
        if any(sub.get("type") == "null" for sub in prop["anyOf"]):
            return " | ".join(sub_types) + " | null"
        return " | ".join(sub_types) if sub_types else "any"

    prop_type = prop.get("type")

    if prop_type == "string":
        if prop.get("format") == "date-time":
            return "string"
        return "string"
    elif prop_type in ("integer", "number"):
        return "number"
    elif prop_type == "boolean":
        return "boolean"
    elif prop_type == "array":
        items = prop.get("items", {})
        item_ts = py_type_to_ts(items, defs)
        return f"{item_ts}[]"
    elif prop_type == "object":
        add_props = prop.get("additionalProperties")
        if isinstance(add_props, dict):
            return f"Record<string, {py_type_to_ts(add_props, defs)}>"
        return "Record<string, any>"

    return "any"


def generate_typescript_interfaces(models: List[Type[BaseModel]]) -> str:
    """Generate TypeScript interfaces from a list of Pydantic models."""
    lines: List[str] = [
        "/**",
        " * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        " * Generated by scripts/export_schemas.py from ingest.models",
        " */",
        "",
    ]

    for model in models:
        schema = model.model_json_schema()
        title = schema.get("title", model.__name__)
        doc = schema.get("description", "")
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        defs = schema.get("$defs", {})

        if doc:
            lines.append("/**")
            for doc_line in doc.strip().split("\n"):
                lines.append(f" * {doc_line}")
            lines.append(" */")

        lines.append(f"export interface {title} {{")
        for prop_name, prop_meta in properties.items():
            desc = prop_meta.get("description")
            if desc:
                lines.append(f"  /** {desc} */")

            is_opt = prop_name not in required
            opt_mark = "?" if is_opt else ""
            ts_type = py_type_to_ts(prop_meta, defs)
            import re
            key_name = prop_name if re.match(r"^[a-zA-Z_$][a-zA-Z0-9_$]*$", prop_name) else f"'{prop_name}'"
            lines.append(f"  {key_name}{opt_mark}: {ts_type};")

        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def export_schemas() -> None:
    repo_root = Path(__file__).resolve().parent.parent

    # 1. Export JSON Schemas to data/schemas/
    schemas_dir = repo_root / "data" / "schemas"
    schemas_dir.mkdir(parents=True, exist_ok=True)

    for model in MODELS:
        schema = model.model_json_schema()
        schema_path = schemas_dir / f"{model.__name__}.schema.json"
        with open(schema_path, "w", encoding="utf-8") as f:
            json.dump(schema, f, indent=2)
        print(f"Exported JSON Schema: {schema_path}")

    # 2. Export TypeScript interfaces to web/src/types/commerce-models.ts
    ts_dir = repo_root / "web" / "src" / "types"
    ts_dir.mkdir(parents=True, exist_ok=True)
    ts_file = ts_dir / "commerce-models.ts"

    ts_content = generate_typescript_interfaces(MODELS)
    with open(ts_file, "w", encoding="utf-8") as f:
        f.write(ts_content)
    print(f"Exported TypeScript interfaces: {ts_file}")

    # Update web/src/types/index.ts to re-export if needed
    index_file = ts_dir / "index.ts"
    if index_file.exists():
        index_content = index_file.read_text(encoding="utf-8")
        export_line = "export * from './commerce-models';"
        if export_line not in index_content:
            with open(index_file, "a", encoding="utf-8") as f:
                f.write(f"\n{export_line}\n")
            print(f"Updated {index_file} with commerce-models re-export")


if __name__ == "__main__":
    export_schemas()
